# create Secrets
apiVersion: v1
kind: Secret
metadata:
  name: gmu-sshcert
  namespace: remo-migrator
  labels:
    app: remo-migrator-cron
  annotations:
    vault.security.banzaicloud.io/vault-addr: https://example.com:8312
    vault.security.banzaicloud.io/vault-path: somepath
    vault.security.banzaicloud.io/vault-role: somerole
    vault.security.banzaicloud.io/vault-skip-verify: "true"
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: qwe
  known_hosts: asd
  ssh_pub_key: zxc
  GITLAB_TOKEN: rty
  BITBUCKET_TOKEN: fgh
  JENKINS_TOKEN: vbn
